### ISSUE TITLE
Base64 encoding of userid and password is not correct

### ISSUE THREAD

**Issue by alfreddeklerk** [xelita/angular-basic-auth#2]
Hi,

I noticed that the base64 encoding in your module is not correct.
your code :
var authData = base64Service.encode(username) + ':' + base64Service.encode(password);

should be:
var authData = base64Service.encode(username + ':' + password);

After this change it worked very well, thank you!
Greetz,
Alfred

**Comment by xelita** [comment]
Hi Alfred.
Take you for the feedback. As asked, the issue has been fixed in the master.
Greetings.
